swagger: "2.0"
info:
  title: API文档
  description: 文档描述
  version: 1.0.0
  contact:
    email: 773683464@qq.com
basePath: /v1
paths:
  /user/useradd:
    post:
      tags:
      - user
      summary: 添加用户
      description: 添加用户
      operationId: UserController.添加用户
      parameters:
      - in: formData
        name: nickname
        description: 昵称
        required: true
        type: string
      - in: formData
        name: openid
        description: openid
        type: string
      - in: formData
        name: wnickname
        description: 微信昵称
        type: string
      - in: formData
        name: wimgurl
        description: 微信头像
        type: string
      - in: formData
        name: mgurl
        description: 头像
        type: string
      - in: formData
        name: gender
        description: 性别1:男2:女3:保密
        type: integer
        format: int64
      - in: formData
        name: age
        description: 年龄
        type: integer
        format: int64
      - in: formData
        name: telphone
        description: 手机号
        type: integer
        format: int64
      - in: formData
        name: qq
        description: QQ
        type: string
      - in: formData
        name: weino
        description: 微博
        type: string
      - in: formData
        name: signature
        description: 个性签名
        type: string
      responses:
        "100":
          description: 错误提示信息!
        "200":
          description: '{<br/> "userid": "用户编号",<br/> "openid": "openid",<br/> "wnickname":
            "微信昵称",<br/> "wimgurl": "微信头像", <br/>"nickname": "昵称",<br/> "imgurl":
            "头像",<br/> "gender":"性别1:男2:女3:保密",<br/> "age":"年龄",<br/> "telphone":"手机号",
            <br/>"QQ": "QQ",<br/> "weino": "微博号", <br/>"signature": "个性签名", <br/>"address":
            "个人地址",<br/> "created_at": "注册时间",<br/>"updated_at":"信息修改时间"<br/> }'
        "500":
          description: 服务器错误!
  /user/userdelete:
    post:
      tags:
      - user
      summary: 删除用户
      description: 删除用户
      operationId: UserController.删除用户
      parameters:
      - in: formData
        name: userid
        description: 用户编号
        required: true
        type: integer
        format: int64
      responses:
        "100":
          description: 错误提示信息!
        "200":
          description: '{<br/> "userid": "用户编号",<br/> }'
        "500":
          description: 服务器错误!
  /user/userlist:
    post:
      tags:
      - user
      summary: 获取用户列表
      description: 获取用户列表
      operationId: UserController.获取用户列表
      parameters:
      - in: formData
        name: start
        description: 获取起始位置
        type: integer
        format: int64
      - in: formData
        name: length
        description: 获取分页步长
        type: integer
        format: int64
      - in: formData
        name: draw
        description: 获取请求次数
        type: integer
        format: int64
      - in: formData
        name: nickname
        description: 昵称
        type: string
      - in: formData
        name: telphone
        description: 手机号
        type: string
      - in: formData
        name: userid
        description: 用户编号
        type: string
      responses:
        "200":
          description: '{<br/> "userid": "用户编号",<br/> "openid": "openid",<br/> "wnickname":
            "微信昵称",<br/> "wimgurl": "微信头像", <br/>"nickname": "昵称",<br/> "imgurl":
            "头像",<br/> "gender":"性别1:男2:女3:保密",<br/> "age":"年龄",<br/> "telphone":"手机号",
            <br/>"QQ": "QQ",<br/> "weino": "微博号", <br/>"signature": "个性签名", <br/>"address":
            "个人地址",<br/> "created_at": "注册时间",<br/>"updated_at":"信息修改时间"<br/> }'
        "500":
          description: 服务器错误!
  /user/userupdate:
    post:
      tags:
      - user
      summary: 修改用户
      description: 修改用户
      operationId: UserController.修改用户
      parameters:
      - in: formData
        name: userid
        description: 用户编号
        required: true
        type: integer
        format: int64
      - in: formData
        name: nickname
        description: 昵称
        type: string
      - in: formData
        name: openid
        description: openid
        type: string
      - in: formData
        name: wnickname
        description: 微信昵称
        type: string
      - in: formData
        name: wimgurl
        description: 微信头像
        type: string
      - in: formData
        name: mgurl
        description: 头像
        type: string
      - in: formData
        name: gender
        description: 性别1:男2:女3:保密
        type: integer
        format: int64
      - in: formData
        name: age
        description: 年龄
        type: integer
        format: int64
      - in: formData
        name: telphone
        description: 手机号
        type: integer
        format: int64
      - in: formData
        name: qq
        description: QQ
        type: string
      - in: formData
        name: weino
        description: 微博
        type: string
      - in: formData
        name: signature
        description: 个性签名
        type: string
      responses:
        "100":
          description: 错误提示信息!
        "200":
          description: '{<br/> "userid": "用户编号",<br/> "openid": "openid",<br/> "wnickname":
            "微信昵称",<br/> "wimgurl": "微信头像", <br/>"nickname": "昵称",<br/> "imgurl":
            "头像",<br/> "gender":"性别1:男2:女3:保密",<br/> "age":"年龄",<br/> "telphone":"手机号",
            <br/>"QQ": "QQ",<br/> "weino": "微博号", <br/>"signature": "个性签名", <br/>"address":
            "个人地址",<br/> "created_at": "注册时间",<br/>"updated_at":"信息修改时间"<br/> }'
        "500":
          description: 服务器错误!
tags:
- name: user
  description: |
    User API
