language: go
go:
  - 1.6.3
  - 1.7.3
  - 1.8
install:
  - go get  github.com/astaxie/beego
  - go get  github.com/astaxie/beego/bee
  - go get  github.com/dgrijalva/jwt-go
  - go get  github.com/garyburd/redigo
  - go get  github.com/go-sql-driver/mysql
script:
  - find . ! \( -path './vendor' -prune \) -type f -name '*.go' -print0 | xargs -0 gofmt -l -s
  - go vet  $(go list ./... | grep -v /vendor/)
  - structcheck  $(go list ./... | grep -v /vendor/)
  - gosimple -ignore "$(cat gosimple.ignore)" $(go list ./... | grep -v /vendor/)
  - staticcheck -ignore "$(cat staticcheck.ignore)" $(go list ./... | grep -v /vendor/)
  - unused $(go list ./... | grep -v /vendor/)
  - unconvert $(go list ./... | grep -v /vendor/)
  - ineffassign .
